- templates/confluence.initscript.erb
Update the initscript
- adapted from:
- https://github.com/bflad/chef-confluence/blob/master/templates/default/confluence.init.erb
- http://confluence.atlassian.com/display/JIRA/Starting+JIRA+Automatically+on+Linux
> Update and add missing LSB information to init script. Resolves issue #9

- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- metadata.json
- spec/classes/coverage_spec.rb
- update README, metadata, .travis.yml
- Add CONTRIBUTING.md and test coverage spec.
> Bump to version 2.1.0

- .sync.yml
- Rakefile
- manifests/init.pp
- manifests/install.pp
> Remove uppercase parameters

- .fixtures.yml
- README.md
- manifests/init.pp
- manifests/install.pp
- metadata.json
- spec/classes/confluence_install_spec.rb
- spec/spec_helper_acceptance.rb
> Use module voxpupuli/archive instead of mkrakowitzer/deploy

- .rubocop.yml
- Rakefile
- spec/acceptance/1_default_parameters_spec.rb
- spec/acceptance/2_default_parameters_upgrade_spec.rb
- spec/acceptance/3_custom_parameters_spec.rb
- spec/classes/confluence_config_spec.rb
- spec/classes/confluence_facts_spec.rb
- spec/classes/confluence_install_spec.rb
- spec/classes/confluence_service_spec.rb
- spec/classes/confluence_spec.rb
- spec/classes/confluence_sso_spec.rb
- spec/classes/confluence_upgrade_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
> Update based on voxpupuli/modulesync_config

- CHANGELOG.md
requested by @rnelson0  in
https://github.com/voxpupuli/puppet-confluence/pull/68
> add note about the original author

- CHANGELOG.md
- CONTRIBUTORS
- manifests/init.pp
- templates/facts.sh.erb
Please check the following items before submitting a PR -- thank you!
Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
tries to address multiple issues. Though we prefer one PR per feature/fix,
sometimes that's not feasible. In that case ensure that a single feature/fix
and associated tests and documentation is bundled up in one commit
Optional, but extra points:
reintroduced
- - -
This may be related to #39 in addition to #74
> Fixes #74 : Correct confluence_version to fix clean install on Puppet 4

- .msync.yml
- Gemfile
- Rakefile
- spec/default_facts.yml
> modulesync 0.11.0

- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- metadata.json
> Modulesync 0.12.1 & Release 2.2.2

- templates/facts.sh.erb
[[ are bash builtin and not supported by sh
> make facts.sh sh compatible

- .msync.yml
> modulesync 0.16.3

- .msync.yml
- .rubocop.yml
- Gemfile
> modulesync 0.16.8

- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- metadata.json
> Modulesync 0.16.11 & Release 2.3.0

- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/sso.pp
- metadata.json
- spec/classes/confluence_config_spec.rb
- spec/classes/confluence_install_spec.rb
- spec/classes/confluence_service_spec.rb
- spec/classes/confluence_spec.rb
- spec/classes/confluence_sso_spec.rb
- spec/classes/confluence_upgrade_spec.rb
> replace validate_* with puppet4 datatypes & fix archive errors

- manifests/init.pp
- spec/classes/confluence_config_spec.rb
> set confluence.home to homedir if data_dir is empty

- .github/CONTRIBUTING.md
- .msync.yml
- .overcommit.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Guardfile
- spec/classes/confluence_config_spec.rb
- spec/classes/confluence_service_spec.rb
- spec/classes/confluence_spec.rb
- spec/classes/confluence_sso_spec.rb
- spec/classes/confluence_upgrade_spec.rb
- spec/spec_helper_acceptance.rb
> modulesync 0.21.0

- manifests/init.pp
> Fix $homedir typo

- manifests/config.pp
Thanks to Chousuke for the help :)
> Fix augeas expression to properly set context path instead of failing silently with multiple contexts

- .gitignore
- .msync.yml
- .rspec_parallel
- .rubocop.yml
- Gemfile
- Guardfile
- spec/acceptance/nodesets/archlinux-2-x64.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
> modulesync 0.21.3

- README.md
- manifests/init.pp
- manifests/install.pp
> Adding proxy support when using 'archive'

- .fixtures.yml
- README.md
- manifests/params.pp
- manifests/service.pp
- metadata.json
- spec/spec_helper_acceptance.rb
> Ubuntu 16.04 Support (systemd) 

- .sync.yml
- manifests/config.pp
- manifests/facts.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/confluence_service_spec.rb
- spec/default_module_facts.yml
- spec/spec_helper.rb
> migrate from topscope variables to facts hash

- README.md
- metadata.json
> bump puppet to latest supported version 4.10.0

- metadata.json
> allow latest puppet/{archive,staging}

- manifests/conf.pp
- manifests/install.pp
I created a little define to change - or audit the properties in confluence.cfg.xml file.
Unfortunately it is only working when the init setup is completed.
Maybe it helps anyway.
> confluence.cfg.xml little automation

- manifests/init.pp
> replace validate_* with assert_type in init.pp

- README.md
- manifests/params.pp
- metadata.json
> Add support for 18.04

- .fixtures.yml
- manifests/init.pp
- manifests/mysql_connector.pp
- metadata.json
- spec/classes/confluence_mysql_connector_spec.rb
This PR deploy mysql connector and copy it to confluence folder
Fixes #34
> Manage mysql connector

- README.md
> Add mysql_connector parameters to README

- README.md
- manifests/mysql_connector.pp
- metadata.json
> drop EOL Ubuntu 14.04

- manifests/mysql_connector.pp
> fix mysql connector source path

- .fixtures.yml
- metadata.json
> allow newer dependencies/drop staging module dep

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .pmtignore
- Gemfile
- metadata.json
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
Bump supported OSes to versions supported by beaker
Fixes #229
> Fix modulesync 7.2.0 tests; Drop Debian/Ubutnu 16.04 support

- metadata.json
This adds stdlib 9 and Puppet 8 compatibility. Didn't break on our side.
n/a
> feat: stdlib9 and puppet8 compatibility

- metadata.json
> add supported OS to fix tests
