- .fixtures.yml
- .travis.yml
- Gemfile
- manifests/init.pp
- manifests/install.pp
- spec/classes/confluence_install_deploy_spec.rb
- spec/classes/confluence_install_staging_spec.rb
- spec/spec_helper_acceptance.rb
Replace mkrakowitzer-deploy with nanliu-staging as the default to deploy
the installation files. nanlui-staging is puppetlabs approved and is
therefore preferred.
> (Issue #5) Replace mkrakowitzer-deploy with nanliu-staging

- metadata.json
The suffix puppet function is used in this module in manifests/config.pp which wasn't introduced in puppetlabs/stdlib until version 4 -- this updates metadata.json accordingly.
> Update metadata.json w/ stdlib 4

- README.markdown
- manifests/init.pp
- manifests/install.pp
- spec/classes/confluence_install_deploy_spec.rb
Setting manage_user to false disables the module managing the user
Allowing it to be managed elsewhere
> Add manage_user parameter

- README.markdown
- manifests/config.pp
- manifests/init.pp
- spec/acceptance/3_custom_parameters_spec.rb
- spec/classes/confluence_config_spec.rb
- templates/server.xml.erb
This commit adds a parameter called "context_path" to the base class and
config class to manage Tomcat's context path.  This is useful for
situations where Confluence is served from a sub-path to the base url.
Managing this with both Augeas and with the server.xml template is
supported.  It defaults to '' (empty string), providing backwards-compatibility and
reasonable defaults.
Should resolve #36 and #21
> Manage context_path

- manifests/service.pp
We need to specified that the systemd file is installed before trying to manage the service. So a little fix that can help others have a very smooth deployment.
> Install systemd file before starting

- README.markdown
- manifests/init.pp
- manifests/install.pp
- spec/acceptance/1_default_parameters_spec.rb
- spec/acceptance/2_default_parameters_upgrade_spec.rb
- spec/acceptance/3_custom_parameters_spec.rb
- spec/classes/confluence_install_deploy_spec.rb
- spec/classes/confluence_install_staging_spec.rb
Add download_url variable as a future replacement for downloadURL in the next major version bump
> Deprecate the downloadURL parameter

- templates/confluence.service.erb
* use $confluence::user param instead of hardcoding "User=confluence"
* set JAVA_HOME for systemd based on $confluence::javahome, as done in JIRA and Stash modules
> centos 7 service template fixes

- README.md
- files/seraph-config_withSSO.xml
- manifests/init.pp
- manifests/sso.pp
- spec/classes/confluence_sso_spec.rb
- templates/crowd.properties
Add crowd's single sign on feature to confluence. When using delegated authentication via Atlassian Crowd, you are able to activate this feature according to Atlassian's documentation at https://confluence.atlassian.com/display/CROWD/Integrating+Crowd+with+Atlassian+Confluence#IntegratingCrowdwithAtlassianConfluence-2.2EnableSSOintegrationwithCrowd
> Add crowd SSO functionality

- CHANGELOG.md
I think someone already tried to deploy 2.2.0. The Changelog was already
prepared and the metadata.json version is bumped. however there isn't a
suitable tag or forge release which I want to fix here.
> prepare for 2.2.0 release

- manifests/install.pp
- spec/classes/confluence_install_spec.rb
When managing the confluence user it defaults to a system user, however this doesn't
apply to the group which may be problematic in deployments where other groups are
hard coded to 1000 which has already been taken by confluence.  Make the confluence
group a system account by default, this appears not to alter existing installations.
> Allow System Group

- manifests/init.pp
- templates/confluence-init.properties.erb
Hi,
modified module to support a data dir which is not the users home e.g: /opt/atlassian/confluence/data. 
Please merge, if tests are ok.
Greets
Taulant
> Added parameter for alternative data dir

- manifests/init.pp
- manifests/install.pp
This PR exposes checksum_verify (as the default for that is 'true' in archive module) in install.pp and exposes it with a conditional in init.pp instead. It sets the value depending on whether checksum is defined by user and performs the check, otherwise it does no check.
@dhoppe @afisher @bbriggs @bastelfreak (and anyone else), please review. Thanks!
> Exposes checksum_verify in init.pp w/ conditional.

- README.md
- manifests/init.pp
- spec/classes/confluence_install_spec.rb
We should use https instead of http, even if Atlassian redirects the traffic automatically.
> Use https instead of http

- manifests/config.pp
- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- templates/server.xml.erb
Partially addresses https://github.com/voxpupuli/puppet-confluence/issues/54
> Add support for configuring an AJP connector

- lib/facter/confluence_version.rb
- spec/unit/facter/util/fact_confluence_version_spec.rb
The facter script was reporting the java version instead of the confluence version. Looking for the first thing on the ps line which looks like a version is not ideal.
Unfortunately the rest API does not seem to provide a version. Jira does; Atlassian are very inconsistent.
This change simply improves on the string matching on the ps line a bit.
This stopped our server from trying to 'upgrade' from 1.8.0 (java version) to 6.0.x.
> Issue 119: updated facter script to not report java version

- spec/classes/confluence_config_spec.rb
- spec/classes/confluence_install_spec.rb
- spec/classes/confluence_service_spec.rb
- spec/classes/confluence_spec.rb
- spec/classes/confluence_sso_spec.rb
- spec/classes/confluence_upgrade_spec.rb
Before this commit, running spec tests on some non-Debian systems would
fail with the message:
```
RuntimeError:
Could not find the daemon directory (tested
[/etc/sv,/var/lib/service])
```
This commit fixes issue #135 by converting each spec test to use a
complete set of sampled fact for each supported OS by using
the `on_supported_os` method from the `rspec-puppet-facts` gem.
> Fix incorrect failures with rspec-puppet-facts

- lib/facter/confluence_version.rb
- spec/unit/facter/util/fact_confluence_version_spec.rb
The long arguments to `pgrep` are not present in older versions of
pgrep, as provided by 'procps'. procps-ng appears to have introduced
these, as used by EL7.
This commit changes the version fact to use `ps ax | grep` to find the
process. It's generic enough and should be supported by the platforms
listed in the module's support matrix.
> Use 'ps' for version fact

- README.md
- manifests/params.pp
- manifests/service.pp
This adds systemd support for Ubuntu 16.04. I also added a `systemctl daemon-reload` for RHEL7 and Ubuntu 16.04 to make sure systemd uses the new unit file when it changes (e.g. during upgrade of confluence).
> Ubuntu 16.04 Support (systemd)

- README.md
- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- templates/setenv.sh.erb
Updates to setenv.sh support CATALINA_OPTS
* Continuation of PR #140 (@joshbeard)
* Support CATALINA_OPTS either as a string or array of strings
* These changes should support making the setenv.sh with minimal changes
from 6.0.x (which is EOL soon) to 6.12.x which was just released.
* Change so the "JAVA_OPTS" part only appear for version prior to Confluence 5.x
* Update README for types and to have an example
* Fixes #155 
* Continue PR #140 (take over)
> Update setenv.sh to support CATALINA_OPTS

- manifests/params.pp
- manifests/service.pp
- metadata.json
- spec/classes/confluence_params_spec.rb
Use service_provider fact to detect systemd for both Debian and RedHat os families. Explicitly (added in metadata.json) adds support for Debian 9, and implicitly (should work without further modification) supports future versions of Ubuntu and RedHat/CentOS.
Fixes #158
> use service_provider fact to detect systemd, support Debian 9

- manifests/install.pp
Confluence (at least as of 6.14.1, maybe it worked in the past) won't start with blank confluence.cfg.xml. Since the presence of this file prevents a fresh confluence install from starting, I propose it simply not be created.
> Don't create confluence.cfg.xml

- templates/setenv.sh.erb
Add support for Java 11 (Confluence added support in v7.1)
No nice way to do it from provided java home, so set with a boolean flag.
Replaces GC logging commands which are no longer recognised with like-for-like Xlog options
> Add support for Java11 (logging options)

- manifests/config.pp
- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- spec/type_aliases/tomcat_attributes_spec.rb
- spec/type_aliases/tomcat_connectors_spec.rb
- templates/server.xml.erb
- types/tomcat_attributes.pp
- types/tomcat_connectors.pp
Add a new, optional class parameter
`confluence::tomcat_additional_connectors` whose value is a well-formed,
complex hash as described by the new type aliases
`Confluence::Tomcat_connectors` and `Confluence::Tomcat_attributes`.
Each hash key represents a port number, and the key's value is a hash
that describes the connector's attributes and their values.
Useful for defining additional HTTP ports through which to access
Confluence.  A typical use case is when Jira and Confluence run behind a
reverse proxy and application links between Jira and Confluence must be
set up.  Then it is often better to allow Jira and Confluence to
communicate directly instead of through the reverse proxy, but this
requires a Tomcat connector that is configured for direct access instead
of reverse proxy access …
> Allow defining additional Tomcat connectors

- .fixtures.yml
- manifests/params.pp
- manifests/service.pp
- metadata.json
The latest version of the systemd module has dropped support for the deamon_reload. It was a workaround, but is not needed anymore since puppet 6.1.
Added a check to avoid calling the reload on puppet > 6.1
> made systemd daemon reload dependent on puppet version; Drop Puppet 5 support

- manifests/install.pp
- spec/classes/confluence_config_spec.rb
Update of PR #198 rebased against master
When `$manage_user=false`, don't permit any resources to `require => User[$confluence::user]` since it does not exist in the catalog.
> If manage_user=false, don't depend on the User resource (obsoletes #198)

- manifests/config.pp
- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- templates/server.xml.erb
This PR allows a user to define a port to redirect to on the default connector using a variable, similarly to tomcat_port. In my case I needed to use manage_server_xml in template mode so I could define an additional connector, which doesn't work with tomcat_extras so I couldn't define it there.
Arguably everything about the default connector should be customisable in server xml template mode, so we could add those if needed also.
Also, somewhat unrelated but tomcat_additional_connectors does not work with the augeaus mode, unless I'm missing something.
N/A
> Add tomcat_redirect_port variable to customise redirectPort in server.xml

- manifests/init.pp
- manifests/install.pp
- spec/classes/confluence_config_spec.rb
- templates/setenv.sh.erb
This integrates the setenv.sh java parameter changes of Confluence 7.12, see this: https://confluence.atlassian.com/doc/confluence-7-12-upgrade-notes-1044092469.html#Confluence7.12UpgradeNotes-setenvfileimprovements
It allows to set parameters depending on the java version, similar like it was done in the puppet-jira module. Also it allows to set options for bigger instances as recommended on the same article linked above.
> Integrated java parameters added or changed in Confluence 7.12

- manifests/config.pp
- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- templates/server.xml.erb
Add variable to be able to configure tomcat's maxHttpHeaderSize attribute.
Default is set to 8192 (from https://tomcat.apache.org/tomcat-9.0-doc/config/http.html `maxHttpHeaderSize: If not specified, this attribute is set to 8192 (8 KB).`)
> Add variable to configure maxHttpHeaderSize attribute

- manifests/init.pp
- spec/classes/confluence_config_spec.rb
- templates/setenv.sh.erb
I stumbled over an issue with JDK17, which is documented here:
https://confluence.atlassian.com/confkb/unrecognized-jvm-gc-options-when-using-jdk-11-17-1002472841.html
This is just a quick fix. I am aware this module needs some love, so this is just the beginning
> add jdk17 option
